"$schema" = 'https://starship.rs/config-schema.json'

format = """
$time\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$status\
$shell\
$username\
$hostname\
$character"""

right_format = """
"""

[aws]
symbol = "ï”­ "
style = "bold yellow"
format = "on [$symbol$profile(\\($region\\))]($style) "
disabled = true
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ "
discharging_symbol = "ğŸ”Œ "
unknown_symbol = "â“ "
empty_symbol = "ğŸª« "
format = "[$symbol$percentage]($style) "
disabled = false
[[battery.display]]
threshold = 10
style = "bold red"
[[battery.display]]
threshold = 20
style = "bold yellow"

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[â®](bold green)"
format = "$symbol "
disabled = false

[cmake]
symbol = "ï¨¶"
style = "bold blue"
format = "via [$symbol$version]($style) "
disabled = false

[cmd_duration]
min_time = 1000
show_milliseconds = false
show_notifications = false
style = "bold yellow"
format = "took [$duration]($style) "
disabled = false

[conda]
truncation_length = 1
symbol = "ğŸ "
style = "bold dimmed green"
format = "[$symbol$environment]($style) "
ignore_base = true
disabled = true

[crystal]
symbol = "ğŸ”® "
style = "bold red"
format = "via [$symbol$version]($style) "
disabled = true

[dart]
symbol = "ğŸ”° "
style = "bold blue"
format = "via [$symbol$version]($style) "
disabled = true

[deno]
symbol = "ğŸ¦• "
style = "green bold"
format = "via [$symbol($version)]($style)"
disabled = true

[directory]
truncation_length = 5
truncate_to_repo = true
use_logical_path = true
fish_style_pwd_dir_length = 0
home_symbol = "~"
truncation_symbol = ""
read_only = "ğŸ”’"
read_only_style = "red"
style = "bold cyan"
format = "[$path]($style)[$read_only]($read_only_style) "
disabled = false

[docker_context]
only_with_files = false
symbol = "ğŸ‹ "
style = "blue bold"
format = "via [$symbol$context]($style) "
disabled = false

[dotnet]
heuristic = true
symbol = "â€¢NET "
style = "bold blue"
format = "via [$symbol$version( ğŸ¯ $tfm)]($style) "
disabled = true

[elixir]
symbol = "ğŸ’§"
style = "bold purple"
format = "via [$symbol$version \\(OTP $otp_version\\)]($style) "
disabled = true

[elm]
symbol = "ğŸŒ³ "
style = "cyan bold"
format = "via [$symbol$version]($style) "
disabled = true

[env_var]
style = "bold dimmed white"
format = "with [$symbol$env_value]($style) "
disabled = true
[env_var.STARSHIP_SHELL]
default = "sh"
symbol = "ï„  "

[erlang]
symbol = "î± "
style = "bold red"
format = "via [$symbol$version]($style) "
disabled = true

[gcloud]
symbol = "ï†  "
style = "bold blue"
format = "on [$symbol$account@$domain(\\($region\\)) - ($project)]($style) "
disabled = true
[gcloud.region_aliases]
us-central1 = "uc1"
asia-northeast1 = "an1"

[git_branch]
truncation_symbol = "â€¦"
symbol = "î‚  "
style = "bold purple"
format = "on [$symbol$branch]($style) "
disabled = false

[git_commit]
commit_hash_length = 8
only_detached = true
tag_symbol = "ğŸ”– "
style = "bold green"
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
tag_disabled = false
disabled = false

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "APPLY-MAILBOX"
am_or_rebase = "AM/REBASE"
style = "dimmed bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
format = '[+$added]($added_style) [-$deleted]($deleted_style) '
disabled = true

[git_status]
conflicted = "=${count} "
ahead = "â‡¡${count} "
behind = "â‡£${count} "
diverged = "â‡¡${ahead_count} â‡£${behind_count} "
untracked = "?${count} "
stashed = "\\$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "Â»${count} "
deleted = "âœ˜${count} "
style = "bold red"
format = "[$all_status$ahead_behind]($style)"
disabled = false

[golang]
symbol = "î˜§ "
style = "bold cyan"
format = "via [$symbol$version]($style) "
disabled = false

[helm]
symbol = "âˆ "
style = "bold white"
format = "via [$symbol$version]($style) "
disabled = true

[hg_branch]
truncation_symbol = "â€¦"
symbol = "ïˆ£ "
style = "bold purple"
format = "on [$symbol$branch]($style) "
disabled = false

[hostname]
ssh_only = false
trim_at = ""
style = "bold yellow"
format = "[$hostname]($style) "
disabled = false

[java]
symbol = "â˜•"
style = "red dimmed"
format = "via [${symbol}${version}]($style) "
disabled = false

[jobs]
threshold = 1
symbol = "âœ¦"
style = "bold yellow"
format = "[$symbol$number]($style) "
disabled = false

[julia]
symbol = "î˜¤ "
style = "bold purple"
format = "via [$symbol$version]($style) "
disabled = true

[kotlin]
kotlin_binary = "kotlin"
symbol = "K "
style = "bold blue"
format = "via [$symbol($version )]($style)"
disabled = true

[kubernetes]
symbol = "â›µ "
style = "cyan bold"
format = "[$symbol$context( \\($namespace\\))]($style) in "
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[line_break]
disabled = false

[lua]
lua_binary = "lua"
symbol = "î˜  "
style = "bold blue"
format = "via [$symbol($version )]($style)"
disabled = false

[memory_usage]
threshold = 75
symbol = "ğŸ "
style = "bold dimmed white"
format = "via $symbol [${ram}( | ${swap})]($style) "
disabled = true

[nim]
symbol = "ğŸ‘‘ "
style = "bold yellow"
format = "via [$symbol$version]($style) "
disabled = true

[nix_shell]
symbol = "ïŒ“ "
impure_msg = "impure"
pure_msg = "pure"
style = "bold blue"
format = 'via [$symbol$state( \($name\))]($style) '
disabled = false

[nodejs]
symbol = "ïŸ— "
style = "bold green"
not_capable_style = "bold red"
format = "via [$symbol$version]($style) "
disabled = false

[ocaml]
symbol = "ğŸ« "
style = "bold yellow"
format = 'via [$symbol($version)(\($switch_indicator$switch_name\) )]($style)'
disabled = true

[openstack]
symbol = "â˜ï¸ "
style = "bold yellow"
format = "on [$symbol$cloud(\\($project\\))]($style) "
disabled = true

[os]
disabled = false
style = "bg:bg fg:fg"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "î˜Ÿ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[package]
display_private = true
symbol = "ğŸ“¦ "
style = "bold 208"
format = "via [$symbol$version]($style) "
disabled = false

[perl]
symbol = "ğŸª "
style = "bold 149"
format = "via [$symbol$version]($style) "
disabled = false

[php]
symbol = "ğŸ˜ "
style = "147 bold"
format = "via [$symbol$version]($style) "
disabled = false

[purescript]
symbol = "<=> "
style = "bold white"
format = "via [$symbol$version]($style) "
disabled = true

[python]
pyenv_version_name = false
pyenv_prefix = "pyenv"
symbol = "ï Ÿ "
style = "yellow bold"
format = "via [${symbol}${pyenv_prefix}${version}( \\($virtualenv\\))]($style) "
disabled = false

[rlang]
symbol = "ğŸ“"
style = "blue bold"
format = "via [$symbol($version )]($style)"
disabled = true

[red]
symbol = "ğŸ”´ "
style = "red bold"
format = "via [$symbol($version )]($style)"
disabled = true

[ruby]
symbol = "ğŸ’ "
style = "bold red"
format = "via [$symbol$version]($style) "
disabled = false

[rust]
symbol = "ğŸ¦€ "
style = "bold red"
format = "via [$symbol$version]($style) "
disabled = false

[scala]
symbol = "îœ· "
style = "red dimmed"
format = "via [${symbol}(${version} )]($style)"
disabled = true

[shell]
disabled = true

[shlvl]
threshold = 2
symbol = "ï½ "
style = "bold yellow"
format = "[$symbol$shlvl]($style) "
disabled = true

[singularity]
symbol = "ï¶ "
style = "bold dimmed blue"
format = "[$symbol\\[$env\\]]($style) "
disabled = true

[status]
symbol = "ğŸ’£ "
not_executable_symbol = "ğŸš«"
not_found_symbol = "ğŸ”"
sigint_symbol = "ğŸ§±"
signal_symbol = "âš¡"
recognize_signal_code = true
map_symbol = true
style = "bold red"
format = "[$symbol$status]($style) "
disabled = true

[swift]
symbol = "ï¯£ "
style = "bold 202"
format = "via [$symbol$version]($style) "
disabled = true

[terraform]
symbol = "ï¯Ÿ "
style = "bold 105"
format = "via [$symbol$version$workspace]($style) "
disabled = false

[time]
use_12hr = false
time_format = "%a %d-%m-%Y %T"
utc_time_offset = "local"
time_range = "00:00:00-23:59:59"
style = "bold bright-green"
format = "[$time]($style) "
disabled = true

[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style)@"
disabled = false

[vagrant]
symbol = "â± "
style = "cyan bold"
format = "via [$symbol($version)]($style) "
disabled = false

[zig]
symbol = "â†¯ "
style = "bold yellow"
format = "via [$symbol$version]($style) "
disabled = false

# add_newline = true
# command_timeout = 200
# format = "[$directory$git_branch$git_status]($style)$character"
#
# [character]
# error_symbol = "[âœ—](bold cyan)"
# success_symbol = "[â¯](bold cyan)"
#
# [directory]
# truncation_length = 2
# truncation_symbol = "â€¦/"
# repo_root_style = "bold cyan"
# repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
#
# [git_branch]
# format = "[$branch]($style) "
# style = "italic cyan"
#
# [git_status]
# format     = '[$all_status]($style)'
# style      = "cyan"
# ahead      = "â‡¡${count} "
# diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
# behind     = "â‡£${count} "
# conflicted = "î®« "
# up_to_date = "ï€Œ "
# untracked  = "? "
# modified   = "î©± "
# stashed    = ""
# staged     = ""
# renamed    = ""
# deleted    = ""
